"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.preprocessEmbeddedTemplates = exports.TEMPLATE_LITERAL_IDENTIFIER = exports.TEMPLATE_LITERAL_MODULE_SPECIFIER = exports.TEMPLATE_TAG_NAME = exports.parseTemplates = void 0;
var parse_templates_1 = require("./parse-templates");
Object.defineProperty(exports, "parseTemplates", { enumerable: true, get: function () { return parse_templates_1.parseTemplates; } });
var util_1 = require("./util");
Object.defineProperty(exports, "TEMPLATE_TAG_NAME", { enumerable: true, get: function () { return util_1.TEMPLATE_TAG_NAME; } });
Object.defineProperty(exports, "TEMPLATE_LITERAL_MODULE_SPECIFIER", { enumerable: true, get: function () { return util_1.TEMPLATE_LITERAL_MODULE_SPECIFIER; } });
Object.defineProperty(exports, "TEMPLATE_LITERAL_IDENTIFIER", { enumerable: true, get: function () { return util_1.TEMPLATE_LITERAL_IDENTIFIER; } });
var preprocess_embedded_templates_1 = require("./preprocess-embedded-templates");
Object.defineProperty(exports, "preprocessEmbeddedTemplates", { enumerable: true, get: function () { return preprocess_embedded_templates_1.preprocessEmbeddedTemplates; } });
